### PR TITLE
AT_18.04_001 | <Profile Page> | Link to User's configure | Configure is displayed on User's profile page

### PR DESCRIPTION
**Pull request by viktoriashidlovskaya**
https://trello.com/c/5ZErR2WG/894-at0000-name

### CODE REVIEW

**Review by a-silanov — APPROVED** [review]

**Comment by KatyaKaterina33** [comment]
Hi. You only check the first acceptance criteria in your test, there are 3 of them in the US.

**Review by Tatsiana-Nazarava — APPROVED** [review]

**Review by OlyaPro — APPROVED** [review]

**Comment by viktoriashidlovskaya** [comment]
> Hi. You only check the first acceptance criteria in your test, there are 3 of them in the US.

of course, i'll do other checks in other tests for this US. so it'll be few tests for one US as Maria told us

**Comment by KatyaKaterina33** [comment]
Sorry, you're right. 
I ran the test on the local computer and it crashed. My username contains uppercase letters so the first test command does not find the locator. To make the test more versatile you can caste the variable "userName" to lowercase:
const userName = Cypress.env("local.admin.username").toLowerCase();

**Comment by viktoriashidlovskaya** [comment]
> Sorry, you're right. I ran the test on the local computer and it crashed. My username contains uppercase letters so the first test command does not find the locator. To make the test more versatile you can caste the variable "userName" to lowercase: const userName = Cypress.env("local.admin.username").toLowerCase();

Thank you for your comment. I will add your suggestion to the test's refactoring

**Pull request merged**
