### PR TITLE
AT_01.01_019 | <Redirection to the homepage by label>

### PR DESCRIPTION
**Pull request by NinaKosova**
[https://trello.com/c/5NxKqADW/380-at0101019-redirection-to-the-homepage-by-label](https://trello.com/c/5NxKqADW/380-at0101019-redirection-to-the-homepage-by-label)

### CODE REVIEW

**Comment by ecatherrina** [comment]
First approve

**Review by OlgaNuriyeva — APPROVED** [review]
Confirmed

**Review by ecatherrina — COMMENTED** [review]
First approve

**Review by EkaterinaGil — APPROVED** [review]
OK

**Review by ecatherrina — APPROVED** [review]

**Pull request merged**
