### PR TITLE
AT_06.01_007 | Verify of url "People" page

### PR DESCRIPTION
**Pull request by Nzs1**
https://trello.com/c/TO88r7lG/1516-at0601007-verify-of-url-people-page

### CODE REVIEW

**Comment by Nzs1** [comment]
[AT_06.01_007 | Verify of url "People" page](https://trello.com/c/TO88r7lG/1516-at0601007-verify-of-url-people-page)

**Review by DariaMas7 — COMMENTED** [review]
Hello. Under one pr should be 1 it(). You pushed two different files, one of them doesn't relate to your branch name and At name. So I would close this PR and start over
Your branch name should include the initials of your First/Last Name / brief description

**Comment by DariaMas7** [comment]
As I can see you have one more PR open
Probably you created a second branch which is verify_Peoplepage from your first branch and not from the main
Its better to work fully under one PR and 1 branch in order to not get confused with branches. So I would highly recommend to save your  code from
 AT_06.01_007 | Verify of url "People" page, close this PR, finish previous one, and after create new branch and PR for people page

**Comment by Nzs1** [comment]
thanks! i see

**Pull request closed without merging**
