### PR TITLE
[ERR] homePage | Verify Homepage Link

### PR DESCRIPTION
**Pull request by matvlesia**
https://trello.com/c/Bv2vcWv4/573-err-homepage-verify-homepage-link-learn-more-about-distributed-builds-is-working

### CODE REVIEW

**Review by engineeryulia — DISMISSED** [review]
LGTM

**Review by Rom-T — CHANGES_REQUESTED** [review]
How was the test corrected? Removing ignore will again lead to the fact that he will again fall on the CI.

**Comment by matvlesia** [comment]
> How was the test corrected? Removing ignore will again lead to the fact that he will again fall on the CI.

I ran the test in Cypress, there weren’t any mistakes. I don't know what should I change

**Comment by Rom-T** [comment]
> > How was the test corrected? Removing ignore will again lead to the fact that he will again fall on the CI.
> 
> I ran the test in Cypress, there weren’t any mistakes. I don't know what should I change

Locally, it passes, but after a time it falls on the SI. You can try adding `{force: true}` to the click like Maria did in #238

**Review by Rom-T — APPROVED** [review]

**Comment by Rom-T** [comment]
In the bottom test, add {force: true}.

**Review by Olga-Khliupina — APPROVED** [review]

**Comment by matvlesia** [comment]
Thank you everyone for advance, I added {force true}

**Review by AnnaDit1 — APPROVED** [review]

**Review by KseniyaParfianovich — APPROVED** [review]

**Review by KseniyaParfianovich — APPROVED** [review]

**Pull request merged**
