### PR TITLE
AT_1.01_004 | Verify Head Icon

### PR DESCRIPTION
**Pull request by Julia-Cherniak**
https://trello.com/c/kMucPjso/168-at101004-verify-that-head-icon-is-visible-and-clickable

### CODE REVIEW

**Review by SvetlanaKazakova — APPROVED** [review]
OK

**Review by QAtrina — APPROVED** [review]

**Review by SvetlanaKazakova — COMMENTED** [review]
OK

**Review by SvetlanaKazakova — COMMENTED** [review]
OK

**Comment by AlisaKapitanova** [comment]
It looks like

**Review by SvetlanaKazakova — COMMENTED** [review]
ok

**Pull request merged**
