### PR TITLE
AT_01.02_023 | Validation of the Search box

### PR DESCRIPTION
**Pull request by Olgret**
Hello, im sorry, i a bit fucked up with pull and push and now, when i want to commit my test there is also update from other files.Otherwise it doesnt let me through. Could smb help?

### CODE REVIEW

**Comment by matvlesia** [comment]
> Hello, im sorry, i a bit fucked up with pull and push and now, when i want to commit my test there is also update from other files.Otherwise it doesnt let me through. Could smb help?

Hi, I think the best way will be to delete this PR and start all over

**Comment by Olgret** [comment]
> 

Hi, i think so too, but thats already my second one, when i make new brunch its the same

**Review by Rom-T — CHANGES_REQUESTED** [review]
Please close PR and create a new branch and PR

**Comment by MariaMoroz** [comment]
Закройте этот пиар пожалуйста.

**Pull request closed without merging**
