### PR TITLE
AT_20.03_003 | Dashboard. Verify dropdown menu is visible

### PR DESCRIPTION
**Pull request by SiarheiMSV**
https://trello.com/c/mTonnNwT/808-at2003003-dashboardjenkins-table-verify-dropdown-menu-of-the-freestyle-project-is-visible

### CODE REVIEW

**Review by IharStankevich — APPROVED** [review]

**Review by IharStankevich — APPROVED** [review]

**Comment by S-Lanchik** [comment]
Please attach the PR link to your AT

**Review by IharStankevich — APPROVED** [review]

**Comment by S-Lanchik** [comment]
I would check in the code that the dropdown list has 6 items (as expected result in your TC).

**Comment by SiarheiMSV** [comment]
I have this assert in another test (AT20.03_002) in the same file.
Each test must have one assert

**Comment by SiarheiMSV** [comment]
I will change the expected result in TC

**Comment by SiarheiMSV** [comment]
> 

done

**Review by zkonovalova78 — APPROVED** [review]

**Pull request merged**
