### PR TITLE
[RF] POM AT_12.10.02 | Verify GiT tooltip text box

### PR DESCRIPTION
**Pull request by EkBlinova**
https://trello.com/c/zAwXFvpO/2136-rf-pom-at121002-freestyle-progect-configure-verify-git-tooltip-text-box-is-visible-and-displays-correct-information-when-user-is

### CODE REVIEW

**Review by DiaTaly — CHANGES_REQUESTED** [review]
You have the word Source misspelled in a couple of places.  It says "Sourse"

**Comment by EkBlinova** [comment]
> You have the word Source misspelled in a couple of places. It says "Sourse"

Oh, I see, thank you.

**Review by DiaTaly — CHANGES_REQUESTED** [review]
Also for tooltip, in some places you have "tooltip", in some "toolTips".  I think it needs to be consistent.  "tooltip" is how it's written in the code.

**Comment by verafes** [comment]
> Also for tooltip, in some places you have "tooltip", in some "toolTips". I think it needs to be consistent. "tooltip" is how it's written in the code.

I would leave  "tooltip", in some "toolTips".  In the future, there could more than one tooltip be added in toolTips fixture for another tests.

**Review by verafes — APPROVED** [review]

**Comment by EkBlinova** [comment]
> Also for tooltip, in some places you have "tooltip", in some "toolTips". I think it needs to be consistent. "tooltip" is how it's written in the code.

Corrected

**Review by DiaTaly — APPROVED** [review]

**Pull request merged**
