### PR TITLE
AT_17.02 _002 | Rename OrgFolder with the same name

### PR DESCRIPTION
**Pull request by ecatherrina**
https://trello.com/c/XAcKZZQV/476-at1702-002-organization-folderrename-organization-folder-with-the-same-name

### CODE REVIEW

**Review by OLgaByR — COMMENTED** [review]
Error текст следует поместить  в fixtures

**Review by verafes — APPROVED** [review]

**Review by Rom-T — APPROVED** [review]

**Comment by NinaKosova** [comment]
ok

**Comment by NinaKosova** [comment]
ok

**Comment by NinaKosova** [comment]
ok

**Comment by NinaKosova** [comment]
ok

**Comment by NinaKosova** [comment]
ok

**Review by NinaKosova — APPROVED** [review]

**Pull request merged**
