### PR TITLE
AT_01.02_003 | <Header> Verify a placeholder text “Search (CTRL+K)" in input field Search box.

### PR DESCRIPTION
**Pull request by milladiz84**
https://trello.com/c/I0ta0Zr6/151-at0102003-header-verify-a-placeholder-text-search-ctrlk-in-input-field-search-box

### CODE REVIEW

**Review by lanasussman — APPROVED** [review]
Good job!

**Review by VolhaChudzesa — APPROVED** [review]

**Review by milia-menzatova — APPROVED** [review]

**Review by LinaAbu1306 — APPROVED** [review]
Good job!

**Review by ellayezina — APPROVED** [review]

**Review by SashaFoxx — APPROVED** [review]
well done

**Review by Rom-T — APPROVED** [review]
LGTM

**Review by TatiChap — APPROVED** [review]
Looks good to me.

**Comment by IrishkaHappiness** [comment]
Great!

**Review by IrishkaHappiness — APPROVED** [review]

**Pull request merged**
