### PR TITLE
AT_01.01_43 | Header| Head Icon is visible and redirects to the homepage

### PR DESCRIPTION
**Pull request by ElenaKanash**
https://trello.com/c/cktqXgQY

### CODE REVIEW

**Review by SvetlanaVet — COMMENTED** [review]
lgtm, but why did you add an empty line after other people's tests? [screen](https://disk.yandex.com/i/ReIIIrIklw91GQ)

**Comment by SvetlanaVet** [comment]
lgtm, but why did you add an empty line after other people's tests?

**Review by AleksaKhouryna — APPROVED** [review]

**Review by SvetlanaVet — APPROVED** [review]

**Comment by ElenaKanash** [comment]
> 

I did not  any empty line after other people's tests. I don't know why these lines are showing as changed

**Review by OLgaByR — APPROVED** [review]
Would it make sense to move  const  on global level( before describe?) in future refactoring , i see others also used it in file

**Pull request merged**
