### PR TITLE
[RF] POM | AT_17.05.02 | <Organization Folder> Verify possibility to enable 'Organization Folder'

### PR DESCRIPTION
**Pull request by allamalitska**
https://trello.com/c/lcHj4VV1/1635-rf-pom-at1705002-verify-possibility-to-enable-organization-folder

### CODE REVIEW

**Comment by allamalitska** [comment]
[[RF] POM | AT_17.05.02 | <Organization Folder> Verify possibility to enable 'Organization Folder'](https://trello.com/c/lcHj4VV1/1635-rf-pom-at170502-organization-folder-verify-possibility-to-enable-organization-folder)

**Review by VeraDoa — APPROVED** [review]

**Comment by S-Lanchik** [comment]
I am not sure if it's crucial but your steps in AT don't match steps in TC.

**Comment by allamalitska** [comment]
> I am not sure if it's crucial but your steps in AT don't match steps in TC.

Could you please write which ones?

**Comment by S-Lanchik** [comment]
> > I am not sure if it's crucial but your steps in AT don't match steps in TC.
> 
> Could you please write which ones?



> > I am not sure if it's crucial but your steps in AT don't match steps in TC.
> 
> Could you please write which ones?

In AT you enable folder right after disabling. In TC the examination starts from homepage, the folder is already disabled. As I wrote before, I am not sure if it's crucial.

**Comment by allamalitska** [comment]
> > > I am not sure if it's crucial but your steps in AT don't match steps in TC.
> > 
> > 
> > Could you please write which ones?
> 
> > > I am not sure if it's crucial but your steps in AT don't match the steps in TC.
> > 
> > 
> > Could you please write which ones?
> 
> In AT you enable folder right after disabling. In TC the examination starts from the homepage, the folder is already disabled. As I wrote before, I am not sure if it's crucial.

There is a second precondition that starts from the homepage, his methods return us to the organization page from which test steps start. The first precondition is taken from the commands, the second is written in the test by using two existing methods.

**Comment by allamalitska** [comment]
I think it matches all that describe in TC. It is not against the rule to write preconditions in the test and not from the commands. Thank you for your comment and for being so careful.  I appreciate it.

**Review by verafes — APPROVED** [review]

**Pull request merged**
