### PR TITLE
AT_01.02_025 | headerSearchBox > accessibility of the search field from the every page

### PR DESCRIPTION
**Pull request by 5daniela**
https://trello.com/c/rbVS8pOp/980-at0102025-accessibility-of-the-search-field-from-the-every-page

### CODE REVIEW

**Review by engineeryulia — APPROVED** [review]
LGTM

**Review by DiscoveryKanel — APPROVED** [review]
great job!

**Review by DiscoveryKanel — APPROVED** [review]

**Review by SvetlanaKanel — APPROVED** [review]
great job!

**Review by Rom-T — COMMENTED** [review]
Well done!

**Pull request merged**
