### PR TITLE
AT_01.07_009 | Verify Redirection to Credential Page from User Dropdown Menu

### PR DESCRIPTION
**Pull request by Nzs1**
https://trello.com/c/TaCxu1q3/1582-at0107009-verify-redirection-to-credential-page-from-user-dropdown-menu

### CODE REVIEW

**Comment by Nzs1** [comment]
[AT_01.07_009 | Verify Redirection to Credential Page from User Dropdown Menu](https://trello.com/c/TaCxu1q3/1582-at0107009-verify-redirection-to-credential-page-from-user-dropdown-menu)

**Comment by S-Lanchik** [comment]
We don't write such tests anymore. We use POM, refactor our tests.

**Review by Rom-T — APPROVED** [review]

**Comment by Rom-T** [comment]
> We don't write such tests anymore. We use POM, refactor our tests.

Of course, we need to rewrite texts under POM. But if it's still hard to do, I think you can add a couple of tests before Maria's next lecture.

**Review by nadilova — APPROVED** [review]

**Comment by Nzs1** [comment]
> > We don't write such tests anymore. We use POM, refactor our tests.
> 
> Of course, we need to rewrite texts under POM. But if it's still hard to do, I think you can add a couple of tests before Maria's next lecture.

ok, I see. Thanks, I will try to rewrite later, because I haven't watched last Maria`s lecture, sorry

**Pull request merged**
