### PR TITLE
AT_01.08_028 | Header Log out button

### PR DESCRIPTION
**Pull request by lina2989**
https://trello.com/c/jDKNH8Z9/916-tc0108028-header-log-out-button

### CODE REVIEW

**Review by ElNov686 — APPROVED** [review]

**Comment by Forostinko** [comment]
You need to change! 1 pull request = 1 It! And write number it

**Comment by Forostinko** [comment]
What are you checking in your test?

**Review by Olgalex — COMMENTED** [review]
Good job

**Comment by Forostinko** [comment]
What are you checking in your test after clicking?

**Pull request merged**
