### PR TITLE
POM>AT_13.02_005 | <Pipeline>Delete project using breadcrumbs dropdown menu

### PR DESCRIPTION
**Pull request by emvrita**
https://trello.com/c/Gc6MQHMO/1820-pomat1302005-pipelinedelete-project-using-breadcrumbs-dropdown-menu

### CODE REVIEW

**Review by olga-kors — APPROVED** [review]

**Comment by KatyaKaterina33** [comment]
If this is a refactoring of an old test please skip this test in old files.

**Comment by emvrita** [comment]
> If this is a refactoring of an old test, please skip this test in the old files. If not, it should be AT-cards instead of Refactoring in Trello.
Its a new test. There is a card that starts with POM without mentioning refactoring and AT card.

**Comment by KatyaKaterina33** [comment]
In Trello I suppose there should be AT card, not Refactoring one.

**Comment by emvrita** [comment]
> In Trello I suppose there should be AT card, not Refactoring one.

I understand what you mean. I decided to do like its done to avoid confusion. If somebody will try to find abandoned test for transferring to POM and will see AT card without POM card, they can start to work on it.

**Pull request merged**
